import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  ChatContainer,
  HomeBody,
  HomeHeader,
  MapContainer,
} from "../components/home/home.styles";
import ChatBox from "@/components/ChatBox/Chat";
import { ChatBody, ChatHeader } from "@/components/ChatBox/Chat.styles";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState([]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeHeader>Header</HomeHeader>
      <HomeBody>
        <MapContainer>MAP</MapContainer>
        <ChatContainer>
          <ChatHeader>ChatHeader</ChatHeader>
          <ChatBody>
            <ChatBox setData={setData}></ChatBox>
          </ChatBody>
        </ChatContainer>
      </HomeBody>
    </>
  );
}
